services:
    entrepids_braintree.form.type.credit_card:
        class: Entrepids\Bundle\BraintreeBundle\Form\Type\CreditCardType
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@security.token_storage'
            - '@translator'
        tags:
            - { name: form.type, alias: entrepids_braintree_credit_card }

    entrepids_braintree.form.type.settings:
        class: Entrepids\Bundle\BraintreeBundle\Form\Type\BraintreeSettingsType
        arguments:
            - '@translator.default'
            - '@oro_security.encoder.mcrypt'
            - '@entrepids_braintree.settings.card_type.provider'
            - '@entrepids_braintree.settings.payment_action.provider'
        tags:
            - { name: form.type }