services:
    entrepids_braintree.integration.channel:
        class: 'Entrepids\Bundle\BraintreeBundle\Integration\BraintreePaymentChannelType'
        public: true
        tags:
            - { name: oro_integration.channel, type: braintree }

    entrepids_braintree.integration.transport:
        class: 'Entrepids\Bundle\BraintreeBundle\Integration\BraintreePaymentsTransport'
        public: false
        tags:
            - { name: oro_integration.transport, type: braintree, channel_type: braintree }
