Entrepids\Bundle\BraintreeBundle\Entity\BraintreeSettings:
    properties:
        braintreeLabel:
            - NotBlank: ~
        braintreeShortLabel:
            - NotBlank: ~
        braintreePaymentAction:
            - NotBlank: ~
            - Valid: ~
        allowedCreditCardTypes:
            - NotBlank: ~
            - Valid: ~
        braintreeEnvironmentType:
            - NotBlank: ~
            - Valid: ~
        braintreeMerchId:
            - NotBlank: ~
            - Valid: ~
        braintreeMerchAccountId:
            - NotBlank: ~
            - Valid: ~
        braintreeMerchPublicKey:
            - NotBlank: ~
            - Valid: ~
        braintreeMerchPrivateKey:
            - NotBlank: ~
            - Valid: ~