config:
    paths:
        'braintree/js/app/components/credit-card-component': 'bundles/braintree/js/app/components/credit-card-component.js'
        'braintree/js/app/components/braintree-checkout-component': 'bundles/braintree/js/app/components/braintree-checkout-component.js'
        'braintree/js/braintree/braintree-client': 'bundles/braintree/js/braintree/braintree-client.js'
        'braintree/js/braintree/braintree-hosted-fields': 'bundles/braintree/js/braintree/braintree-hosted-fields.js'
