parameters:
    entrepids_braintree.method.identifier_prefix.braintree: 'braintree'
services:
    entrepids_braintree.provider.credit_form_provider:
        class: 'Entrepids\Bundle\BraintreeBundle\Layout\DataProvider\CreditCardFormProvider'
        arguments:
            - '@form.factory'
            - '@router'
        tags:
            - { name: layout.data_provider, alias: entrepids_braintree_credit_card_form_provider }
 
    entrepids_braintree.settings.payment_action.provider:
        class: Entrepids\Bundle\BraintreeBundle\Settings\DataProvider\BasicPaymentActionsDataProvider

    entrepids_braintree.settings.card_type.provider:
        class: Entrepids\Bundle\BraintreeBundle\Settings\DataProvider\BasicCardTypesDataProvider
        
    entrepids_braintree.generator.braintree_config_identifier:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - '%entrepids_braintree.method.identifier_prefix.braintree%'
 
    entrepids_braintree.repository.braintree_settings:
        class: 'Entrepids\Bundle\BraintreeBundle\Entity\Repository\BraintreeSettingsRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Entrepids\Bundle\BraintreeBundle\Entity\BraintreeSettings'
            