services:

    entrepids_braintree.braintree.payflow.client.http:
        class: 'Guzzle\Http\Client'
        public: false
        lazy: true
        
    entrepids_braintree.event_listener.callback.braintree:
        class: 'Entrepids\Bundle\BraintreeBundle\EventListener\Callback\BraintreeCheckoutListener'
        lazy: true
        arguments:
            - '@entrepids_braintree.payment_method_provider.braintree'
        calls:
            - ['setLogger', ['@logger']]
        tags:
            - { name: kernel.event_listener, event: oro_payment.callback.error.braintree, method: onError }
            - { name: kernel.event_listener, event: oro_payment.callback.return.braintree, method: onReturn }
           