placeholders:
    placeholders:
        view_general_section_after:
            items:
                payment_braintree_info: ~

    items:
        payment_braintree_info:
            template: EntrepidsBraintreeBundle:PaymentTransaction:info.html.twig
            data: '@entrepids_braintree.provider.payment_info->getPaymentInfo($entity$)'
            applicable: "@entrepids_braintree.provider.payment_info->isApplicable($entity$)"